vich_uploader:
    db_driver: orm

    mappings:
        aircraft:
            uri_prefix: uploads/images/aircraft
            upload_destination: '%kernel.project_dir%/public/uploads/images/aircraft'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        aircraft_document:
            uri_prefix: uploads/documents/aircraft_document
            upload_destination: '%kernel.project_dir%/public/uploads/documents/aircraft_document'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        aircraft_video:
            uri_prefix: uploads/video/aircraft_video
            upload_destination: '%kernel.project_dir%/public/uploads/video/aircraft_video'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        article_image:
            uri_prefix: uploads/blog/article_image
            upload_destination: '%kernel.project_dir%/public/uploads/blog/article_image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        article_image_affiche:
            uri_prefix: uploads/blog/article_image_affiche
            upload_destination: '%kernel.project_dir%/public/uploads/blog/article_image_affiche'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        article_section_image:
            uri_prefix: uploads/blog/article_section_image
            upload_destination: '%kernel.project_dir%/public/uploads/blog/article_section_image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
